main: com.paperbenni.setup.Setup
load: POSTWORLD
version: 1.0
name: mineglory_plugin
author: paperbenni
description: this is just a test plugin
commands:
  hello:
    description: sends a hello message which is beautiful
  equip:
    description: sends a goodbye message which is beautiful
  mobateam:
    description: sends a player to another team
  gold:
    description: allows you to modify the gold balances of players
  mhelp: 
    description: a help command for mineglory
  minion: 
    description: minion commands